Fix TypeScript build error
node_modules/parse5/dist/tokenizer/index.d.ts:3:31 - error TS2307: Cannot find module 'entities/decode' or its corresponding type declarations.
There are types at '/home/marcin/projekty/push-to-kindle2/node-readability/node_modules/entities/dist/decode.d.ts', but this result could not be resolved under your current 'moduleResolution' setting.
Consider updating to 'node16', 'nodenext', or 'bundler'.